version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:root@mysql-db:3306/flask_db
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SECRET_KEY=zixalTEst
    depends_on:
      - mysql-db
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8070:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
